openapi: 3.0.1
info:
  title: Application
  description: Generated at 06/10/2024 07:42:26. This is the swagger 
    ui based on the open api 3.0 specification of the Application
  version: 1.0.0 created by the flask swagger generator.
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: '/'
paths:
  '/swagger/dist/{filename}':
    get:
      tags:
      - swagger_ui
      operationId: 'static'
      parameters:
      - in: path
        name: filename
        schema:
          type: string
        description: None
        required: True
  '/swagger/{path}':
    get:
      tags:
      - swagger_ui
      operationId: 'show'
      parameters:
      - in: path
        name: path
        schema:
          type: string
        description: None
        required: True
  '/swagger/':
    get:
      tags:
      - swagger_ui
      operationId: 'show'
  '/dapr/subscribe':
    get:
      tags:
      - None
      operationId: '/dapr/subscribe'
  '/healtz':
    get:
      tags:
      - None
      operationId: 'health'
      responses:
        '200':
          $ref: '#/components/responses/health_response'
  '/train_model':
    get:
      tags:
      - None
      operationId: 'train_model'
  '/download_data':
    get:
      tags:
      - None
      operationId: 'download_data_from_azure'
  '/events/ai-pubsub/start-download-data':
    post:
      tags:
      - None
      operationId: '/events/ai-pubsub/start-download-data'
  '/test_model':
    get:
      tags:
      - None
      operationId: 'start_test_model'
  '/start_train_model':
    get:
      tags:
      - None
      operationId: 'start_train_model'
  '/events/ai-pubsub/start-train-model':
    post:
      tags:
      - None
      operationId: '/events/ai-pubsub/start-train-model'
components:
  responses:
    health_response:
      description: health response
      content:
         application/json:
             schema:
                 $ref: '#/components/schemas/health_response_schema'
  schemas:
    health_response_schema:
      type: object
