name: DataExporter
on:
  push:
    branches: ["main"]
    paths:
      [
        "csharp/Common/**",
        "csharp/DataExporter/**",
        ".github/workflows/dataexporter.yaml",
      ]
permissions:
  contents: read
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./csharp
          file: ./csharp/DataExporter/Dockerfile
          platforms: |
            linux/arm64
            linux/amd64
          push: true
          tags: neichmann/dataexporter:app-${{ github.run_number }}
  # modifygit:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       name: changing the values of git repo
  #       with:
  #         repository: 'enicky/LabPowerConsumptionPrediction'
  #         token: ${{ secrets.GIT_TOKEN }}
  #     - name: modify the image
  #       run: |
  #         git config user.email enicky80@gmail.com
  #         git config user.name enicky
  #         cd DataExporter
  #         pwd
  #         cat values.yaml
  #         pwd
  #         sed -i "s+app-[0-9]*\"+app-$RUN_NUMBER\"+g" values.yaml
  #         cat values.yaml
  #         git add .
  #         git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
  #         git push origin main
  #       env:
  #         GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  #         GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  #         RUN_NUMBER: ${{ github.run_number }}
  ##Following was the original code, but it was not used in the end.
#  modifygit:
#    needs: docker
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        name: changing the values of git repo
#        with:
#          repository: "enicky/cluster-template"
#          token: ${{ secrets.GIT_TOKEN }}
#      - name: list-cluster-template
#        run: |  
#          ls -la kubernetes/apps/home
#      - name: modify the image
#        run: |
#          git config user.email enicky80@gmail.com
#          git config user.name enicky
#          cd kubernetes/apps/home/ai/dataexporter
#          pwd
#          cat values.yaml
#          pwd
#          sed -i "s+app-[0-9]*\"+app-$RUN_NUMBER\"+g" values.yaml
#          cat values.yaml
#          git add .
#          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
#          git push origin main
#        env:
#          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
#          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
#          RUN_NUMBER: ${{ github.run_number }}
