name: pythontrainer
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'python/**'
      - '.github/workflows/pythonaitrainer.yaml'
      - '!python/Dockerfile.base'
permissions:
  contents: read
jobs:
  docker:
    name: Build Docker Image for PythonAI
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          cd python/
          ls -la
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          provenance: false
          context: ./python
          file: ./python/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: neichmann/pythonaitrainer:app-${{ github.run_number }},neichmann/pythonaitrainer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the values of git repo
        with:
          repository: 'enicky/LabPowerConsumptionPrediction'
          token: ${{ secrets.GIT_TOKEN }}
      - name: modify the image
        run: |
          git config user.email enicky80@gmail.com
          git config user.name enicky
          cd PythonAiTrainer
          pwd
          cat values.yaml
          pwd
          echo "----- start SED -------"
          sed -i "s+app-[0-9]*\"+app-$RUN_NUMBER\"+g" values.yaml
          echo "----- finished SED ----"
          cat values.yaml
          echo "======================="
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
