name: SonarCloud - SchedulerService
on:
  workflow_dispatch:
  push:
    paths:
      [
        "csharp/Common/**",
        "csharp/SchedulerService/**",
        "csharp/Tests/SchedulerService.Tests/**",
        "csharp/Tests/Common.Tests/**",
        ".github/workflows/sonarcloud_schedulerservice.yaml",
        ".github/workflows/schedulerservice.yaml",
      ]
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      [
        "csharp/Common/**",
        "csharp/SchedulerService/**",
        "csharp/Tests/SchedulerService.Tests/**",
        "csharp/Tests/Common.Tests/**",
        ".github/workflows/sonarcloud_schedulerservice.yaml",
        ".github/workflows/schedulerservice.yaml",
      ]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu" # Alternative distribution options are available.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install sonar dotnet coverage tool
        shell: bash
        run: |
          dotnet tool install --global dotnet-coverage
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_VERBOSE: "true"
        shell: bash
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin -X /k:"enicky_schedulerservice" \
            /o:"enicky" /d:sonar.token="${SONAR_TOKEN}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.cobertura.reportsPaths=coverage.cobertura.xml \
            /d:sonar.scanner.scanAll=false

          dotnet restore ./csharp/SchedulerService/SchedulerService.csproj
          dotnet restore ./csharp/Common/Common.csproj

          dotnet build ./csharp/SchedulerService/SchedulerService.csproj --no-incremental --no-restore
          dotnet build ./csharp/Common/Common.csproj --no-incremental --no-restore


          # Run tests and collect coverage for both test projects using coverlet collector
          dotnet test ./csharp/Tests/SchedulerService.Tests/SchedulerService.Tests.csproj --collect:"XPlat Code Coverage"
          cp ./csharp/Tests/SchedulerService.Tests/TestResults/**/coverage.cobertura.xml coverage1.cobertura.xml

          dotnet test ./csharp/Tests/Common.Tests/Common.Tests.csproj --collect:"XPlat Code Coverage"
          cp ./csharp/Tests/Common.Tests/TestResults/**/coverage.cobertura.xml coverage2.cobertura.xml

          # Merge coverage reports
          reportgenerator -reports:"coverage1.cobertura.xml;coverage2.cobertura.xml" -targetdir:coverage-report -reporttypes:Cobertura

          # The merged file will be at coverage-report/Cobertura.xml
          cp coverage-report/Cobertura.xml coverage.cobertura.xml

          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
      - uses: actions/upload-artifact@v4
        with:
          path: coverage.cobertura.xml
